// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/models/shared"
	"net/http"
)

type AdvanceUserAssignmentRequest struct {
	// Group id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *AdvanceUserAssignmentRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type AdvanceUserAssignmentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Updated user group with crt_assignee updated to next user in line
	Group *shared.Group
}

func (o *AdvanceUserAssignmentResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AdvanceUserAssignmentResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AdvanceUserAssignmentResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *AdvanceUserAssignmentResponse) GetGroup() *shared.Group {
	if o == nil {
		return nil
	}
	return o.Group
}
