// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/models/shared"
	"net/http"
)

type BeginPasskeyRegistrationRequestBody struct {
	FriendlyName *string `json:"friendly_name,omitempty"`
}

func (b *BeginPasskeyRegistrationRequestBody) GetFriendlyName() *string {
	if b == nil {
		return nil
	}
	return b.FriendlyName
}

type BeginPasskeyRegistrationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// WebAuthn registration options
	PasskeyRegistrationOptions *shared.PasskeyRegistrationOptions
}

func (b *BeginPasskeyRegistrationResponse) GetContentType() string {
	if b == nil {
		return ""
	}
	return b.ContentType
}

func (b *BeginPasskeyRegistrationResponse) GetStatusCode() int {
	if b == nil {
		return 0
	}
	return b.StatusCode
}

func (b *BeginPasskeyRegistrationResponse) GetRawResponse() *http.Response {
	if b == nil {
		return nil
	}
	return b.RawResponse
}

func (b *BeginPasskeyRegistrationResponse) GetPasskeyRegistrationOptions() *shared.PasskeyRegistrationOptions {
	if b == nil {
		return nil
	}
	return b.PasskeyRegistrationOptions
}
