// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/models/shared"
	"net/http"
)

type BeginDiscoverablePasskeyAuthenticationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// WebAuthn discoverable authentication options
	PasskeyAuthenticationOptions *shared.PasskeyAuthenticationOptions
}

func (b *BeginDiscoverablePasskeyAuthenticationResponse) GetContentType() string {
	if b == nil {
		return ""
	}
	return b.ContentType
}

func (b *BeginDiscoverablePasskeyAuthenticationResponse) GetStatusCode() int {
	if b == nil {
		return 0
	}
	return b.StatusCode
}

func (b *BeginDiscoverablePasskeyAuthenticationResponse) GetRawResponse() *http.Response {
	if b == nil {
		return nil
	}
	return b.RawResponse
}

func (b *BeginDiscoverablePasskeyAuthenticationResponse) GetPasskeyAuthenticationOptions() *shared.PasskeyAuthenticationOptions {
	if b == nil {
		return nil
	}
	return b.PasskeyAuthenticationOptions
}
