// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/models/shared"
	"net/http"
)

type DeleteUserV2Request struct {
	// The Id of user
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteUserV2Request) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

// #region class-body-deleteuserv2request
// #endregion class-body-deleteuserv2request

type DeleteUserV2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The deleted user
	User *shared.User
}

func (d *DeleteUserV2Response) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteUserV2Response) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteUserV2Response) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteUserV2Response) GetUser() *shared.User {
	if d == nil {
		return nil
	}
	return d.User
}

// #region class-body-deleteuserv2response
// #endregion class-body-deleteuserv2response
