// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteUserSettingRequest struct {
	// User setting scope
	Scope string `pathParam:"style=simple,explode=false,name=scope"`
	// User setting key
	Key string `pathParam:"style=simple,explode=false,name=key"`
}

func (d *DeleteUserSettingRequest) GetScope() string {
	if d == nil {
		return ""
	}
	return d.Scope
}

func (d *DeleteUserSettingRequest) GetKey() string {
	if d == nil {
		return ""
	}
	return d.Key
}

type DeleteUserSettingResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (d *DeleteUserSettingResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteUserSettingResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteUserSettingResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}
