// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/models/shared"
	"net/http"
)

type GetGroupsRequest struct {
	// Query name to filter by
	Query *string `queryParam:"style=form,explode=true,name=query"`
	// Limit the results size
	Limit *float64 `queryParam:"style=form,explode=true,name=limit"`
	// Specify the offset
	Offset *float64 `queryParam:"style=form,explode=true,name=offset"`
	// Pass it true when you want to hydrate the group with full user details
	Hydrate *bool `queryParam:"style=form,explode=true,name=hydrate"`
}

func (g *GetGroupsRequest) GetQuery() *string {
	if g == nil {
		return nil
	}
	return g.Query
}

func (g *GetGroupsRequest) GetLimit() *float64 {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GetGroupsRequest) GetOffset() *float64 {
	if g == nil {
		return nil
	}
	return g.Offset
}

func (g *GetGroupsRequest) GetHydrate() *bool {
	if g == nil {
		return nil
	}
	return g.Hydrate
}

// GetGroupsResponseBody - List of groups
type GetGroupsResponseBody struct {
	Hits   *float64       `json:"hits,omitempty"`
	Groups []shared.Group `json:"groups,omitempty"`
}

func (g *GetGroupsResponseBody) GetHits() *float64 {
	if g == nil {
		return nil
	}
	return g.Hits
}

func (g *GetGroupsResponseBody) GetGroups() []shared.Group {
	if g == nil {
		return nil
	}
	return g.Groups
}

type GetGroupsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of groups
	Object *GetGroupsResponseBody
}

func (g *GetGroupsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetGroupsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetGroupsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetGroupsResponse) GetObject() *GetGroupsResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
