// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/models/shared"
	"net/http"
)

type GetGroupRequest struct {
	// Group id
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Pass it true when you want to hydrate the group with full user details
	Hydrate *bool `queryParam:"style=form,explode=true,name=hydrate"`
}

func (o *GetGroupRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetGroupRequest) GetHydrate() *bool {
	if o == nil {
		return nil
	}
	return o.Hydrate
}

type GetGroupResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Group
	Group *shared.Group
}

func (o *GetGroupResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetGroupResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetGroupResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetGroupResponse) GetGroup() *shared.Group {
	if o == nil {
		return nil
	}
	return o.Group
}
