// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/models/shared"
	"net/http"
)

type GetGroupsForUserRequest struct {
	// The Id of user
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetGroupsForUserRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetGroupsForUserResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The returned user groups
	Groups []shared.Group
}

func (g *GetGroupsForUserResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetGroupsForUserResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetGroupsForUserResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetGroupsForUserResponse) GetGroups() []shared.Group {
	if g == nil {
		return nil
	}
	return g.Groups
}
