// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/models/shared"
	"net/http"
)

type GetMeV2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// currently logged in user
	UserV2 *shared.UserV2
}

func (g *GetMeV2Response) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetMeV2Response) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetMeV2Response) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetMeV2Response) GetUserV2() *shared.UserV2 {
	if g == nil {
		return nil
	}
	return g.UserV2
}
