// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/models/shared"
	"net/http"
)

type GetNavigationRequest struct {
	// The UUID of the navigation
	ID *string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetNavigationRequest) GetID() *string {
	if g == nil {
		return nil
	}
	return g.ID
}

type GetNavigationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The navigation configuration
	Navigation *shared.Navigation
}

func (g *GetNavigationResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetNavigationResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetNavigationResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetNavigationResponse) GetNavigation() *shared.Navigation {
	if g == nil {
		return nil
	}
	return g.Navigation
}
