// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/models/shared"
	"net/http"
)

type GetUserLoginParametersRequest struct {
	// Username
	Username string `pathParam:"style=simple,explode=false,name=username"`
}

func (g *GetUserLoginParametersRequest) GetUsername() string {
	if g == nil {
		return ""
	}
	return g.Username
}

// GetUserLoginParametersResponseBody - User
type GetUserLoginParametersResponseBody struct {
	LoginParameters []shared.LoginParameters `json:"login_parameters,omitempty"`
}

func (g *GetUserLoginParametersResponseBody) GetLoginParameters() []shared.LoginParameters {
	if g == nil {
		return nil
	}
	return g.LoginParameters
}

type GetUserLoginParametersResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// User
	Object *GetUserLoginParametersResponseBody
}

func (g *GetUserLoginParametersResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetUserLoginParametersResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetUserLoginParametersResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetUserLoginParametersResponse) GetObject() *GetUserLoginParametersResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
