// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/models/shared"
	"net/http"
)

type GetUserV2Request struct {
	// The Id of user
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetUserV2Request) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetUserV2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The returned user
	UserV2 *shared.UserV2
}

func (o *GetUserV2Response) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetUserV2Response) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetUserV2Response) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetUserV2Response) GetUserV2() *shared.UserV2 {
	if o == nil {
		return nil
	}
	return o.UserV2
}
