// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/models/shared"
	"net/http"
)

type GetUserSettingsScopeRequest struct {
	// User setting scope, for example calendar, navigation, or search
	Scope string `pathParam:"style=simple,explode=false,name=scope"`
}

func (g *GetUserSettingsScopeRequest) GetScope() string {
	if g == nil {
		return ""
	}
	return g.Scope
}

type GetUserSettingsScopeResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// User settings for the requested scope
	UserSettingsScopeResponse *shared.UserSettingsScopeResponse
}

func (g *GetUserSettingsScopeResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetUserSettingsScopeResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetUserSettingsScopeResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetUserSettingsScopeResponse) GetUserSettingsScopeResponse() *shared.UserSettingsScopeResponse {
	if g == nil {
		return nil
	}
	return g.UserSettingsScopeResponse
}
