// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/models/shared"
	"net/http"
)

type GetUserSettingRequest struct {
	// User setting scope
	Scope string `pathParam:"style=simple,explode=false,name=scope"`
	// User setting key
	Key string `pathParam:"style=simple,explode=false,name=key"`
}

func (g *GetUserSettingRequest) GetScope() string {
	if g == nil {
		return ""
	}
	return g.Scope
}

func (g *GetUserSettingRequest) GetKey() string {
	if g == nil {
		return ""
	}
	return g.Key
}

type GetUserSettingResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// User setting
	UserSetting *shared.UserSetting
}

func (g *GetUserSettingResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetUserSettingResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetUserSettingResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetUserSettingResponse) GetUserSetting() *shared.UserSetting {
	if g == nil {
		return nil
	}
	return g.UserSetting
}
