// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/models/shared"
	"net/http"
)

type GetUserLoginParametersV2Request struct {
	// Username
	Username string `pathParam:"style=simple,explode=false,name=username"`
}

func (o *GetUserLoginParametersV2Request) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}

// GetUserLoginParametersV2ResponseBody - User
type GetUserLoginParametersV2ResponseBody struct {
	LoginParameters []shared.LoginParameters `json:"login_parameters,omitempty"`
}

func (o *GetUserLoginParametersV2ResponseBody) GetLoginParameters() []shared.LoginParameters {
	if o == nil {
		return nil
	}
	return o.LoginParameters
}

type GetUserLoginParametersV2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// User
	Object *GetUserLoginParametersV2ResponseBody
}

func (o *GetUserLoginParametersV2Response) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetUserLoginParametersV2Response) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetUserLoginParametersV2Response) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetUserLoginParametersV2Response) GetObject() *GetUserLoginParametersV2ResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
