// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/models/shared"
	"net/http"
)

type InviteUserResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Invited successfully
	UserV2 *shared.UserV2
}

func (i *InviteUserResponse) GetContentType() string {
	if i == nil {
		return ""
	}
	return i.ContentType
}

func (i *InviteUserResponse) GetStatusCode() int {
	if i == nil {
		return 0
	}
	return i.StatusCode
}

func (i *InviteUserResponse) GetRawResponse() *http.Response {
	if i == nil {
		return nil
	}
	return i.RawResponse
}

func (i *InviteUserResponse) GetUserV2() *shared.UserV2 {
	if i == nil {
		return nil
	}
	return i.UserV2
}
