// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/models/shared"
	"net/http"
)

type ListUsersV2Request struct {
	// Query text to filter by
	Query *string `queryParam:"style=form,explode=true,name=query"`
	// Limit the results size
	Limit *float64 `queryParam:"style=form,explode=true,name=limit"`
	// Specify the offset
	Offset *float64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *ListUsersV2Request) GetQuery() *string {
	if o == nil {
		return nil
	}
	return o.Query
}

func (o *ListUsersV2Request) GetLimit() *float64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListUsersV2Request) GetOffset() *float64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// ListUsersV2ResponseBody - List of organization users
type ListUsersV2ResponseBody struct {
	Results []shared.UserV2 `json:"results,omitempty"`
}

func (o *ListUsersV2ResponseBody) GetResults() []shared.UserV2 {
	if o == nil {
		return nil
	}
	return o.Results
}

type ListUsersV2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of organization users
	Object *ListUsersV2ResponseBody
}

func (o *ListUsersV2Response) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListUsersV2Response) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListUsersV2Response) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListUsersV2Response) GetObject() *ListUsersV2ResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
