// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/models/shared"
	"net/http"
)

type ListUsersV2Request struct {
	// Query text to filter by
	Query *string `queryParam:"style=form,explode=true,name=query"`
	// Limit the results size
	Limit *float64 `queryParam:"style=form,explode=true,name=limit"`
	// Specify the offset
	Offset *float64 `queryParam:"style=form,explode=true,name=offset"`
}

func (l *ListUsersV2Request) GetQuery() *string {
	if l == nil {
		return nil
	}
	return l.Query
}

func (l *ListUsersV2Request) GetLimit() *float64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListUsersV2Request) GetOffset() *float64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

// #region class-body-listusersv2request
// #endregion class-body-listusersv2request

// ListUsersV2ResponseBody - List of organization users
type ListUsersV2ResponseBody struct {
	Results []shared.UserV2 `json:"results,omitempty"`
}

func (l *ListUsersV2ResponseBody) GetResults() []shared.UserV2 {
	if l == nil {
		return nil
	}
	return l.Results
}

// #region class-body-listusersv2responsebody
// #endregion class-body-listusersv2responsebody

type ListUsersV2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of organization users
	Object *ListUsersV2ResponseBody
}

func (l *ListUsersV2Response) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListUsersV2Response) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListUsersV2Response) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListUsersV2Response) GetObject() *ListUsersV2ResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}

// #region class-body-listusersv2response
// #endregion class-body-listusersv2response
