// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/models/shared"
	"net/http"
)

type ListUsersRequest struct {
	// Comma-separated list of organization ids to filter by
	OrgIds []string `queryParam:"style=form,explode=false,name=org_ids"`
	// Query text to filter by
	Query *string `queryParam:"style=form,explode=true,name=query"`
	// Limit the results size
	Limit *float64 `queryParam:"style=form,explode=true,name=limit"`
	// Specify the offset
	Offset *float64 `queryParam:"style=form,explode=true,name=offset"`
}

func (l *ListUsersRequest) GetOrgIds() []string {
	if l == nil {
		return nil
	}
	return l.OrgIds
}

func (l *ListUsersRequest) GetQuery() *string {
	if l == nil {
		return nil
	}
	return l.Query
}

func (l *ListUsersRequest) GetLimit() *float64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListUsersRequest) GetOffset() *float64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

// ListUsersResponseBody - List of users
type ListUsersResponseBody struct {
	Users []shared.User `json:"users,omitempty"`
}

func (l *ListUsersResponseBody) GetUsers() []shared.User {
	if l == nil {
		return nil
	}
	return l.Users
}

type ListUsersResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of users
	Object *ListUsersResponseBody
}

func (l *ListUsersResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListUsersResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListUsersResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListUsersResponse) GetObject() *ListUsersResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
