// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/models/shared"
	"net/http"
)

// ListPasskeysResponseBody - List of passkeys
type ListPasskeysResponseBody struct {
	Passkeys []shared.Passkey `json:"passkeys,omitempty"`
}

func (l *ListPasskeysResponseBody) GetPasskeys() []shared.Passkey {
	if l == nil {
		return nil
	}
	return l.Passkeys
}

type ListPasskeysResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of passkeys
	Object *ListPasskeysResponseBody
}

func (l *ListPasskeysResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListPasskeysResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListPasskeysResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListPasskeysResponse) GetObject() *ListPasskeysResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
