// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/models/shared"
	"net/http"
)

type PutUserSettingRequest struct {
	// User setting scope
	Scope string `pathParam:"style=simple,explode=false,name=scope"`
	// User setting key
	Key         string `pathParam:"style=simple,explode=false,name=key"`
	RequestBody any    `request:"mediaType=application/json"`
}

func (p *PutUserSettingRequest) GetScope() string {
	if p == nil {
		return ""
	}
	return p.Scope
}

func (p *PutUserSettingRequest) GetKey() string {
	if p == nil {
		return ""
	}
	return p.Key
}

func (p *PutUserSettingRequest) GetRequestBody() any {
	if p == nil {
		return nil
	}
	return p.RequestBody
}

type PutUserSettingResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// User setting saved successfully
	UserSetting *shared.UserSetting
}

func (p *PutUserSettingResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PutUserSettingResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PutUserSettingResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PutUserSettingResponse) GetUserSetting() *shared.UserSetting {
	if p == nil {
		return nil
	}
	return p.UserSetting
}
