// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type RejectInviteRequest struct {
	// Invite Token
	Token string `queryParam:"style=form,explode=true,name=token"`
}

func (r *RejectInviteRequest) GetToken() string {
	if r == nil {
		return ""
	}
	return r.Token
}

// RejectInviteResponseBody - Rejected invite successfully
type RejectInviteResponseBody struct {
	Success *bool `json:"success,omitempty"`
}

func (r *RejectInviteResponseBody) GetSuccess() *bool {
	if r == nil {
		return nil
	}
	return r.Success
}

type RejectInviteResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Rejected invite successfully
	Object *RejectInviteResponseBody
}

func (r *RejectInviteResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *RejectInviteResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *RejectInviteResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}

func (r *RejectInviteResponse) GetObject() *RejectInviteResponseBody {
	if r == nil {
		return nil
	}
	return r.Object
}
