// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type RejectInviteRequest struct {
	// Invite Token
	Token string `queryParam:"style=form,explode=true,name=token"`
}

func (o *RejectInviteRequest) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}

// RejectInviteResponseBody - Rejected invite successfully
type RejectInviteResponseBody struct {
	Success *bool `json:"success,omitempty"`
}

func (o *RejectInviteResponseBody) GetSuccess() *bool {
	if o == nil {
		return nil
	}
	return o.Success
}

type RejectInviteResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Rejected invite successfully
	Object *RejectInviteResponseBody
}

func (o *RejectInviteResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *RejectInviteResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *RejectInviteResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *RejectInviteResponse) GetObject() *RejectInviteResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
