// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type RequestPasswordResetRequestBody struct {
	// Email address of the account to reset
	Email string `json:"email"`
}

func (r *RequestPasswordResetRequestBody) GetEmail() string {
	if r == nil {
		return ""
	}
	return r.Email
}

// RequestPasswordResetResponseBody - Request accepted
type RequestPasswordResetResponseBody struct {
	Message string `json:"message"`
}

func (r *RequestPasswordResetResponseBody) GetMessage() string {
	if r == nil {
		return ""
	}
	return r.Message
}

type RequestPasswordResetResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Request accepted
	Object *RequestPasswordResetResponseBody
}

func (r *RequestPasswordResetResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *RequestPasswordResetResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *RequestPasswordResetResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}

func (r *RequestPasswordResetResponse) GetObject() *RequestPasswordResetResponseBody {
	if r == nil {
		return nil
	}
	return r.Object
}
