// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"net/http"
)

type ResetPasswordRequestBody struct {
	// Email address of the account
	Email string `json:"email"`
	// Reset token from the password reset email
	Token string `json:"token"`
	// The new password
	Password string `json:"password"`
}

func (r *ResetPasswordRequestBody) GetEmail() string {
	if r == nil {
		return ""
	}
	return r.Email
}

func (r *ResetPasswordRequestBody) GetToken() string {
	if r == nil {
		return ""
	}
	return r.Token
}

func (r *ResetPasswordRequestBody) GetPassword() string {
	if r == nil {
		return ""
	}
	return r.Password
}

// Error - Discriminator distinguishing token errors from policy errors
type Error string

const (
	ErrorInvalidResetLink Error = "INVALID_RESET_LINK"
	ErrorPasswordPolicy   Error = "PASSWORD_POLICY"
)

func (e Error) ToPointer() *Error {
	return &e
}
func (e *Error) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "INVALID_RESET_LINK":
		fallthrough
	case "PASSWORD_POLICY":
		*e = Error(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Error: %v", v)
	}
}

type Violations string

const (
	ViolationsTooShort         Violations = "too_short"
	ViolationsMissingLowercase Violations = "missing_lowercase"
	ViolationsMissingUppercase Violations = "missing_uppercase"
	ViolationsMissingNumber    Violations = "missing_number"
	ViolationsMissingSymbol    Violations = "missing_symbol"
)

func (e Violations) ToPointer() *Violations {
	return &e
}
func (e *Violations) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "too_short":
		fallthrough
	case "missing_lowercase":
		fallthrough
	case "missing_uppercase":
		fallthrough
	case "missing_number":
		fallthrough
	case "missing_symbol":
		*e = Violations(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Violations: %v", v)
	}
}

// ResetPasswordUserV2ResponseBody - Invalid or expired reset link, or password does not meet the requirements
type ResetPasswordUserV2ResponseBody struct {
	// Discriminator distinguishing token errors from policy errors
	Error   Error  `json:"error"`
	Message string `json:"message"`
	// Itemized password-policy violation codes (only present when error is PASSWORD_POLICY)
	Violations []Violations `json:"violations,omitempty"`
}

func (r *ResetPasswordUserV2ResponseBody) GetError() Error {
	if r == nil {
		return Error("")
	}
	return r.Error
}

func (r *ResetPasswordUserV2ResponseBody) GetMessage() string {
	if r == nil {
		return ""
	}
	return r.Message
}

func (r *ResetPasswordUserV2ResponseBody) GetViolations() []Violations {
	if r == nil {
		return nil
	}
	return r.Violations
}

// #region class-body-resetpassworduserv2responsebody
// #endregion class-body-resetpassworduserv2responsebody

// ResetPasswordResponseBody - Password reset successfully
type ResetPasswordResponseBody struct {
	Success bool `json:"success"`
}

func (r *ResetPasswordResponseBody) GetSuccess() bool {
	if r == nil {
		return false
	}
	return r.Success
}

type ResetPasswordResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Password reset successfully
	TwoHundredApplicationJSONObject *ResetPasswordResponseBody
	// Invalid or expired reset link, or password does not meet the requirements
	FourHundredApplicationJSONObject *ResetPasswordUserV2ResponseBody
}

func (r *ResetPasswordResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *ResetPasswordResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *ResetPasswordResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}

func (r *ResetPasswordResponse) GetTwoHundredApplicationJSONObject() *ResetPasswordResponseBody {
	if r == nil {
		return nil
	}
	return r.TwoHundredApplicationJSONObject
}

func (r *ResetPasswordResponse) GetFourHundredApplicationJSONObject() *ResetPasswordUserV2ResponseBody {
	if r == nil {
		return nil
	}
	return r.FourHundredApplicationJSONObject
}
