// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/models/shared"
	"net/http"
)

// AssertionResponse - WebAuthn AuthenticatorAssertionResponse JSON
type AssertionResponse struct {
}

type ResolveDiscoverableCredentialRequestBody struct {
	// The challenge token from authenticateBeginDiscoverable
	ChallengeToken string `json:"challenge_token"`
	// WebAuthn AuthenticatorAssertionResponse JSON
	AssertionResponse AssertionResponse `json:"assertion_response"`
}

func (r *ResolveDiscoverableCredentialRequestBody) GetChallengeToken() string {
	if r == nil {
		return ""
	}
	return r.ChallengeToken
}

func (r *ResolveDiscoverableCredentialRequestBody) GetAssertionResponse() AssertionResponse {
	if r == nil {
		return AssertionResponse{}
	}
	return r.AssertionResponse
}

// ResolveDiscoverableCredentialResponseBody - Resolved user identity and login parameters
type ResolveDiscoverableCredentialResponseBody struct {
	Email           *string                  `json:"email,omitempty"`
	OrganizationID  *string                  `json:"organization_id,omitempty"`
	UserID          *string                  `json:"user_id,omitempty"`
	LoginParameters []shared.LoginParameters `json:"login_parameters,omitempty"`
}

func (r *ResolveDiscoverableCredentialResponseBody) GetEmail() *string {
	if r == nil {
		return nil
	}
	return r.Email
}

func (r *ResolveDiscoverableCredentialResponseBody) GetOrganizationID() *string {
	if r == nil {
		return nil
	}
	return r.OrganizationID
}

func (r *ResolveDiscoverableCredentialResponseBody) GetUserID() *string {
	if r == nil {
		return nil
	}
	return r.UserID
}

func (r *ResolveDiscoverableCredentialResponseBody) GetLoginParameters() []shared.LoginParameters {
	if r == nil {
		return nil
	}
	return r.LoginParameters
}

type ResolveDiscoverableCredentialResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Resolved user identity and login parameters
	Object *ResolveDiscoverableCredentialResponseBody
}

func (r *ResolveDiscoverableCredentialResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *ResolveDiscoverableCredentialResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *ResolveDiscoverableCredentialResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}

func (r *ResolveDiscoverableCredentialResponse) GetObject() *ResolveDiscoverableCredentialResponseBody {
	if r == nil {
		return nil
	}
	return r.Object
}
