// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type SendUserPasswordResetRequestBody struct {
	// Email address of the user to reset
	Email string `json:"email"`
}

func (s *SendUserPasswordResetRequestBody) GetEmail() string {
	if s == nil {
		return ""
	}
	return s.Email
}

// SendUserPasswordResetResponseBody - Password reset triggered
type SendUserPasswordResetResponseBody struct {
	Success bool `json:"success"`
}

func (s *SendUserPasswordResetResponseBody) GetSuccess() bool {
	if s == nil {
		return false
	}
	return s.Success
}

type SendUserPasswordResetResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Password reset triggered
	Object *SendUserPasswordResetResponseBody
}

func (s *SendUserPasswordResetResponse) GetContentType() string {
	if s == nil {
		return ""
	}
	return s.ContentType
}

func (s *SendUserPasswordResetResponse) GetStatusCode() int {
	if s == nil {
		return 0
	}
	return s.StatusCode
}

func (s *SendUserPasswordResetResponse) GetRawResponse() *http.Response {
	if s == nil {
		return nil
	}
	return s.RawResponse
}

func (s *SendUserPasswordResetResponse) GetObject() *SendUserPasswordResetResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
