// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/models/shared"
	"net/http"
)

type SignUpUserRequest struct {
	// Partner invitation token
	Token             *string                   `queryParam:"style=form,explode=true,name=token"`
	SignupUserPayload *shared.SignupUserPayload `request:"mediaType=application/json"`
}

func (s *SignUpUserRequest) GetToken() *string {
	if s == nil {
		return nil
	}
	return s.Token
}

func (s *SignUpUserRequest) GetSignupUserPayload() *shared.SignupUserPayload {
	if s == nil {
		return nil
	}
	return s.SignupUserPayload
}

// SignUpUserResponseBody - The created user and organization
type SignUpUserResponseBody struct {
	User         *shared.User         `json:"user,omitempty"`
	Organization *shared.Organization `json:"organization,omitempty"`
}

func (s *SignUpUserResponseBody) GetUser() *shared.User {
	if s == nil {
		return nil
	}
	return s.User
}

func (s *SignUpUserResponseBody) GetOrganization() *shared.Organization {
	if s == nil {
		return nil
	}
	return s.Organization
}

type SignUpUserResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The created user and organization
	Object *SignUpUserResponseBody
}

func (s *SignUpUserResponse) GetContentType() string {
	if s == nil {
		return ""
	}
	return s.ContentType
}

func (s *SignUpUserResponse) GetStatusCode() int {
	if s == nil {
		return 0
	}
	return s.StatusCode
}

func (s *SignUpUserResponse) GetRawResponse() *http.Response {
	if s == nil {
		return nil
	}
	return s.RawResponse
}

func (s *SignUpUserResponse) GetObject() *SignUpUserResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
