// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type SwitchOrganizationRequestBody struct {
	OrgID string `json:"org_id"`
}

func (s *SwitchOrganizationRequestBody) GetOrgID() string {
	if s == nil {
		return ""
	}
	return s.OrgID
}

// SwitchOrganizationResponseBody - A login token for the new organization to be used with CUSTOM_AUTH flow
type SwitchOrganizationResponseBody struct {
	// A login token for the new organization to be used with CUSTOM_AUTH flow against login parameters
	LoginToken string `json:"login_token"`
}

func (s *SwitchOrganizationResponseBody) GetLoginToken() string {
	if s == nil {
		return ""
	}
	return s.LoginToken
}

type SwitchOrganizationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A login token for the new organization to be used with CUSTOM_AUTH flow
	Object *SwitchOrganizationResponseBody
}

func (s *SwitchOrganizationResponse) GetContentType() string {
	if s == nil {
		return ""
	}
	return s.ContentType
}

func (s *SwitchOrganizationResponse) GetStatusCode() int {
	if s == nil {
		return 0
	}
	return s.StatusCode
}

func (s *SwitchOrganizationResponse) GetRawResponse() *http.Response {
	if s == nil {
		return nil
	}
	return s.RawResponse
}

func (s *SwitchOrganizationResponse) GetObject() *SwitchOrganizationResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
