// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/models/shared"
	"net/http"
)

type UpdateGroupRequest struct {
	// Group id
	ID             string                 `pathParam:"style=simple,explode=false,name=id"`
	UpdateGroupReq *shared.UpdateGroupReq `request:"mediaType=application/json"`
}

func (o *UpdateGroupRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateGroupRequest) GetUpdateGroupReq() *shared.UpdateGroupReq {
	if o == nil {
		return nil
	}
	return o.UpdateGroupReq
}

type UpdateGroupResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Group created successfully
	Group *shared.Group
}

func (o *UpdateGroupResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateGroupResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateGroupResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateGroupResponse) GetGroup() *shared.Group {
	if o == nil {
		return nil
	}
	return o.Group
}
