// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/models/shared"
	"net/http"
)

type UpdateUserV2Request struct {
	// The Id of user
	ID     string              `pathParam:"style=simple,explode=false,name=id"`
	UserV2 *shared.UserV2Input `request:"mediaType=application/json"`
}

func (u *UpdateUserV2Request) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateUserV2Request) GetUserV2() *shared.UserV2Input {
	if u == nil {
		return nil
	}
	return u.UserV2
}

type UpdateUserV2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The returned user
	UserV2 *shared.UserV2
}

func (u *UpdateUserV2Response) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateUserV2Response) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateUserV2Response) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateUserV2Response) GetUserV2() *shared.UserV2 {
	if u == nil {
		return nil
	}
	return u.UserV2
}
