// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/models/shared"
	"net/http"
)

type VerifyEmailWithTokenRequest struct {
	// Verification Token
	Token                   string                          `queryParam:"style=form,explode=true,name=token"`
	UserVerificationPayload *shared.UserVerificationPayload `request:"mediaType=application/json"`
}

func (o *VerifyEmailWithTokenRequest) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}

func (o *VerifyEmailWithTokenRequest) GetUserVerificationPayload() *shared.UserVerificationPayload {
	if o == nil {
		return nil
	}
	return o.UserVerificationPayload
}

type VerifyEmailWithTokenResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *VerifyEmailWithTokenResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *VerifyEmailWithTokenResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *VerifyEmailWithTokenResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
