// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CognitoDetails struct {
	CognitoRegion           *string `json:"cognito_region,omitempty"`
	CognitoUserPoolID       *string `json:"cognito_user_pool_id,omitempty"`
	CognitoUserPoolClientID *string `json:"cognito_user_pool_client_id,omitempty"`
	CognitoUserPoolArn      *string `json:"cognito_user_pool_arn,omitempty"`
}

func (o *CognitoDetails) GetCognitoRegion() *string {
	if o == nil {
		return nil
	}
	return o.CognitoRegion
}

func (o *CognitoDetails) GetCognitoUserPoolID() *string {
	if o == nil {
		return nil
	}
	return o.CognitoUserPoolID
}

func (o *CognitoDetails) GetCognitoUserPoolClientID() *string {
	if o == nil {
		return nil
	}
	return o.CognitoUserPoolClientID
}

func (o *CognitoDetails) GetCognitoUserPoolArn() *string {
	if o == nil {
		return nil
	}
	return o.CognitoUserPoolArn
}
