// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CognitoDetails struct {
	CognitoRegion           *string `json:"cognito_region,omitempty"`
	CognitoUserPoolID       *string `json:"cognito_user_pool_id,omitempty"`
	CognitoUserPoolClientID *string `json:"cognito_user_pool_client_id,omitempty"`
	CognitoUserPoolArn      *string `json:"cognito_user_pool_arn,omitempty"`
}

func (c *CognitoDetails) GetCognitoRegion() *string {
	if c == nil {
		return nil
	}
	return c.CognitoRegion
}

func (c *CognitoDetails) GetCognitoUserPoolID() *string {
	if c == nil {
		return nil
	}
	return c.CognitoUserPoolID
}

func (c *CognitoDetails) GetCognitoUserPoolClientID() *string {
	if c == nil {
		return nil
	}
	return c.CognitoUserPoolClientID
}

func (c *CognitoDetails) GetCognitoUserPoolArn() *string {
	if c == nil {
		return nil
	}
	return c.CognitoUserPoolArn
}
