// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateGroupReq struct {
	// The name of the group. Could be a department or a team.
	Name string `json:"name"`
}

func (o *CreateGroupReq) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
