// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateGroupReq struct {
	// The name of the group. Could be a department or a team.
	Name string `json:"name"`
	// The list of user ids in the group.
	UserIds []string `json:"user_ids,omitempty"`
}

func (o *CreateGroupReq) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateGroupReq) GetUserIds() []string {
	if o == nil {
		return nil
	}
	return o.UserIds
}
