// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateGroupReq struct {
	// The name of the group. Could be a department or a team.
	Name string `json:"name"`
	// Group's profile image or gradient colors. Supports uploaded image URLs and generated gradient avatars.
	ImageURI *GroupImageURI `json:"image_uri,omitempty"`
}

func (c *CreateGroupReq) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateGroupReq) GetImageURI() *GroupImageURI {
	if c == nil {
		return nil
	}
	return c.ImageURI
}
