// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/internal/utils"
)

// GroupImageURI - Group's profile image or gradient colors. Supports uploaded image URLs and generated gradient avatars.
type GroupImageURI struct {
	Original    *string `json:"original,omitempty"`
	Thumbnail32 *string `json:"thumbnail_32,omitempty"`
	Thumbnail64 *string `json:"thumbnail_64,omitempty"`
	// Two hex color strings [base_color, accent_color] for mesh gradient avatar.
	GradientColors       []string `json:"gradient_colors,omitempty"`
	AdditionalProperties any      `additionalProperties:"true" json:"-"`
}

func (g GroupImageURI) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GroupImageURI) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GroupImageURI) GetOriginal() *string {
	if g == nil {
		return nil
	}
	return g.Original
}

func (g *GroupImageURI) GetThumbnail32() *string {
	if g == nil {
		return nil
	}
	return g.Thumbnail32
}

func (g *GroupImageURI) GetThumbnail64() *string {
	if g == nil {
		return nil
	}
	return g.Thumbnail64
}

func (g *GroupImageURI) GetGradientColors() []string {
	if g == nil {
		return nil
	}
	return g.GradientColors
}

func (g *GroupImageURI) GetAdditionalProperties() any {
	if g == nil {
		return nil
	}
	return g.AdditionalProperties
}
