// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Group struct {
	// Group unique identifier
	ID string `json:"id"`
	// The name of the group. Could be a department or a team.
	Name string `json:"name"`
}

func (g *Group) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *Group) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}
