// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Group struct {
	// Group unique identifier
	ID string `json:"id"`
	// The name of the group. Could be a department or a team.
	Name string `json:"name"`
}

func (o *Group) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Group) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
