// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type OauthResponseType string

const (
	OauthResponseTypeCode  OauthResponseType = "code"
	OauthResponseTypeToken OauthResponseType = "token"
)

func (e OauthResponseType) ToPointer() *OauthResponseType {
	return &e
}
func (e *OauthResponseType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "code":
		fallthrough
	case "token":
		*e = OauthResponseType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OauthResponseType: %v", v)
	}
}

type LoginParameters struct {
	OrganizationID          *string            `json:"organization_id,omitempty"`
	OrganizationName        *string            `json:"organization_name,omitempty"`
	OrganizationType        *string            `json:"organization_type,omitempty"`
	OrganizationUse         *string            `json:"organization_use,omitempty"`
	CognitoRegion           *string            `json:"cognito_region,omitempty"`
	CognitoUserPoolID       *string            `json:"cognito_user_pool_id,omitempty"`
	CognitoUserPoolClientID *string            `json:"cognito_user_pool_client_id,omitempty"`
	CognitoOauthDomain      *string            `json:"cognito_oauth_domain,omitempty"`
	CognitoOauthScopes      []string           `json:"cognito_oauth_scopes,omitempty"`
	OauthResponseType       *OauthResponseType `json:"oauth_response_type,omitempty"`
	// Whether passkey login is enabled for this organization
	PasskeyEnabled *bool `json:"passkey_enabled,omitempty"`
}

func (l *LoginParameters) GetOrganizationID() *string {
	if l == nil {
		return nil
	}
	return l.OrganizationID
}

func (l *LoginParameters) GetOrganizationName() *string {
	if l == nil {
		return nil
	}
	return l.OrganizationName
}

func (l *LoginParameters) GetOrganizationType() *string {
	if l == nil {
		return nil
	}
	return l.OrganizationType
}

func (l *LoginParameters) GetOrganizationUse() *string {
	if l == nil {
		return nil
	}
	return l.OrganizationUse
}

func (l *LoginParameters) GetCognitoRegion() *string {
	if l == nil {
		return nil
	}
	return l.CognitoRegion
}

func (l *LoginParameters) GetCognitoUserPoolID() *string {
	if l == nil {
		return nil
	}
	return l.CognitoUserPoolID
}

func (l *LoginParameters) GetCognitoUserPoolClientID() *string {
	if l == nil {
		return nil
	}
	return l.CognitoUserPoolClientID
}

func (l *LoginParameters) GetCognitoOauthDomain() *string {
	if l == nil {
		return nil
	}
	return l.CognitoOauthDomain
}

func (l *LoginParameters) GetCognitoOauthScopes() []string {
	if l == nil {
		return nil
	}
	return l.CognitoOauthScopes
}

func (l *LoginParameters) GetOauthResponseType() *OauthResponseType {
	if l == nil {
		return nil
	}
	return l.OauthResponseType
}

func (l *LoginParameters) GetPasskeyEnabled() *bool {
	if l == nil {
		return nil
	}
	return l.PasskeyEnabled
}
