// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/internal/utils"
)

// NavigationGroupItem - A navigation group containing sub-items
type NavigationGroupItem struct {
	// The display name of the navigation group
	Name string `json:"name"`
	// The list of navigation items within this group
	SubItems []NavigationKeyItem `json:"subItems"`
}

func (n NavigationGroupItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NavigationGroupItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *NavigationGroupItem) GetName() string {
	if n == nil {
		return ""
	}
	return n.Name
}

func (n *NavigationGroupItem) GetSubItems() []NavigationKeyItem {
	if n == nil {
		return []NavigationKeyItem{}
	}
	return n.SubItems
}
