// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/internal/utils"
)

// NavigationKeyItem - A simple navigation item with a key
type NavigationKeyItem struct {
	// The unique key identifier for the navigation item
	Key string `json:"key"`
}

func (n NavigationKeyItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NavigationKeyItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *NavigationKeyItem) GetKey() string {
	if n == nil {
		return ""
	}
	return n.Key
}
