// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// Navigation - A customized workplace navigation configuration. The ID is a content-hash, so identical configurations will have the same ID.
type Navigation struct {
	// Navigation unique identifier - a hash of the normalized navigation payload (name + configuration). Identical navigations across orgs will have the same ID.
	ID *string `json:"id"`
	// Human-readable name for the navigation configuration
	Name string `json:"name"`
	// Navigation configuration organized by sections. Each section contains an array of navigation items.
	//
	Configuration map[string][]NavigationItem `json:"configuration"`
}

func (n *Navigation) GetID() *string {
	if n == nil {
		return nil
	}
	return n.ID
}

func (n *Navigation) GetName() string {
	if n == nil {
		return ""
	}
	return n.Name
}

func (n *Navigation) GetConfiguration() map[string][]NavigationItem {
	if n == nil {
		return map[string][]NavigationItem{}
	}
	return n.Configuration
}
