// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// NavigationCreateRequest - Request payload to create a new navigation configuration
type NavigationCreateRequest struct {
	// Human-readable name for the navigation configuration
	Name string `json:"name"`
	// Navigation configuration organized by sections. Each section contains an array of navigation items.
	//
	Configuration map[string][]NavigationItem `json:"configuration"`
}

func (n *NavigationCreateRequest) GetName() string {
	if n == nil {
		return ""
	}
	return n.Name
}

func (n *NavigationCreateRequest) GetConfiguration() map[string][]NavigationItem {
	if n == nil {
		return map[string][]NavigationItem{}
	}
	return n.Configuration
}
