// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/internal/utils"
)

type NavigationItemType string

const (
	NavigationItemTypeNavigationKeyItem   NavigationItemType = "NavigationKeyItem"
	NavigationItemTypeNavigationGroupItem NavigationItemType = "NavigationGroupItem"
)

// NavigationItem - A navigation item - either a simple key item or a group with sub-items
type NavigationItem struct {
	NavigationKeyItem   *NavigationKeyItem   `queryParam:"inline" union:"member"`
	NavigationGroupItem *NavigationGroupItem `queryParam:"inline" union:"member"`

	Type NavigationItemType
}

func CreateNavigationItemNavigationKeyItem(navigationKeyItem NavigationKeyItem) NavigationItem {
	typ := NavigationItemTypeNavigationKeyItem

	return NavigationItem{
		NavigationKeyItem: &navigationKeyItem,
		Type:              typ,
	}
}

func CreateNavigationItemNavigationGroupItem(navigationGroupItem NavigationGroupItem) NavigationItem {
	typ := NavigationItemTypeNavigationGroupItem

	return NavigationItem{
		NavigationGroupItem: &navigationGroupItem,
		Type:                typ,
	}
}

func (u *NavigationItem) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var navigationKeyItem NavigationKeyItem = NavigationKeyItem{}
	if err := utils.UnmarshalJSON(data, &navigationKeyItem, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  NavigationItemTypeNavigationKeyItem,
			Value: &navigationKeyItem,
		})
	}

	var navigationGroupItem NavigationGroupItem = NavigationGroupItem{}
	if err := utils.UnmarshalJSON(data, &navigationGroupItem, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  NavigationItemTypeNavigationGroupItem,
			Value: &navigationGroupItem,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for NavigationItem", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for NavigationItem", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(NavigationItemType)
	switch best.Type {
	case NavigationItemTypeNavigationKeyItem:
		u.NavigationKeyItem = best.Value.(*NavigationKeyItem)
		return nil
	case NavigationItemTypeNavigationGroupItem:
		u.NavigationGroupItem = best.Value.(*NavigationGroupItem)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for NavigationItem", string(data))
}

func (u NavigationItem) MarshalJSON() ([]byte, error) {
	if u.NavigationKeyItem != nil {
		return utils.MarshalJSON(u.NavigationKeyItem, "", true)
	}

	if u.NavigationGroupItem != nil {
		return utils.MarshalJSON(u.NavigationGroupItem, "", true)
	}

	return nil, errors.New("could not marshal union type NavigationItem: all fields are null")
}
