// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/internal/utils"
)

type Type string

const (
	TypeVendor  Type = "Vendor"
	TypePartner Type = "Partner"
)

func (e Type) ToPointer() *Type {
	return &e
}
func (e *Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Vendor":
		fallthrough
	case "Partner":
		*e = Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Type: %v", v)
	}
}

type OrganizationDetail struct {
	Type                        Type    `json:"type"`
	Name                        string  `json:"name"`
	PricingTier                 string  `json:"pricing_tier"`
	Email                       string  `json:"email"`
	Phone                       *string `json:"phone,omitempty"`
	Website                     *string `json:"website,omitempty"`
	IsPrivacyPolicyChecked      *bool   `json:"is_privacy_policy_checked,omitempty"`
	IsTermsAndConditionsChecked *bool   `json:"is_terms_and_conditions_checked,omitempty"`
	AdditionalProperties        any     `additionalProperties:"true" json:"-"`
}

func (o OrganizationDetail) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OrganizationDetail) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *OrganizationDetail) GetType() Type {
	if o == nil {
		return Type("")
	}
	return o.Type
}

func (o *OrganizationDetail) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *OrganizationDetail) GetPricingTier() string {
	if o == nil {
		return ""
	}
	return o.PricingTier
}

func (o *OrganizationDetail) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *OrganizationDetail) GetPhone() *string {
	if o == nil {
		return nil
	}
	return o.Phone
}

func (o *OrganizationDetail) GetWebsite() *string {
	if o == nil {
		return nil
	}
	return o.Website
}

func (o *OrganizationDetail) GetIsPrivacyPolicyChecked() *bool {
	if o == nil {
		return nil
	}
	return o.IsPrivacyPolicyChecked
}

func (o *OrganizationDetail) GetIsTermsAndConditionsChecked() *bool {
	if o == nil {
		return nil
	}
	return o.IsTermsAndConditionsChecked
}

func (o *OrganizationDetail) GetAdditionalProperties() any {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}
