// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// PasskeyRegistrationOptionsOptions - WebAuthn PublicKeyCredentialCreationOptions
type PasskeyRegistrationOptionsOptions struct {
}

type PasskeyRegistrationOptions struct {
	// WebAuthn PublicKeyCredentialCreationOptions
	Options *PasskeyRegistrationOptionsOptions `json:"options,omitempty"`
	// Signed JWT containing the challenge
	ChallengeToken *string `json:"challenge_token,omitempty"`
}

func (p *PasskeyRegistrationOptions) GetOptions() *PasskeyRegistrationOptionsOptions {
	if p == nil {
		return nil
	}
	return p.Options
}

func (p *PasskeyRegistrationOptions) GetChallengeToken() *string {
	if p == nil {
		return nil
	}
	return p.ChallengeToken
}
