// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/internal/utils"
	"time"
)

type Passkey struct {
	// Base64url-encoded credential ID
	CredentialID *string    `json:"credential_id,omitempty"`
	FriendlyName *string    `json:"friendly_name,omitempty"`
	CreatedAt    *time.Time `json:"created_at,omitempty"`
	Transports   []string   `json:"transports,omitempty"`
	Aaguid       *string    `json:"aaguid,omitempty"`
}

func (p Passkey) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Passkey) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *Passkey) GetCredentialID() *string {
	if p == nil {
		return nil
	}
	return p.CredentialID
}

func (p *Passkey) GetFriendlyName() *string {
	if p == nil {
		return nil
	}
	return p.FriendlyName
}

func (p *Passkey) GetCreatedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.CreatedAt
}

func (p *Passkey) GetTransports() []string {
	if p == nil {
		return nil
	}
	return p.Transports
}

func (p *Passkey) GetAaguid() *string {
	if p == nil {
		return nil
	}
	return p.Aaguid
}
