// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// RegistrationResponse - WebAuthn AuthenticatorAttestationResponse
type RegistrationResponse struct {
}

type PasskeyRegistrationResponse struct {
	// The challenge token from registerBegin
	ChallengeToken string `json:"challenge_token"`
	// WebAuthn AuthenticatorAttestationResponse
	RegistrationResponse RegistrationResponse `json:"registration_response"`
	FriendlyName         *string              `json:"friendly_name,omitempty"`
}

func (p *PasskeyRegistrationResponse) GetChallengeToken() string {
	if p == nil {
		return ""
	}
	return p.ChallengeToken
}

func (p *PasskeyRegistrationResponse) GetRegistrationResponse() RegistrationResponse {
	if p == nil {
		return RegistrationResponse{}
	}
	return p.RegistrationResponse
}

func (p *PasskeyRegistrationResponse) GetFriendlyName() *string {
	if p == nil {
		return nil
	}
	return p.FriendlyName
}
