// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// OptionsObj - WebAuthn PublicKeyCredentialRequestOptions
type OptionsObj struct {
}

type PasskeyAuthenticationOptions struct {
	// WebAuthn PublicKeyCredentialRequestOptions
	Options *OptionsObj `json:"options,omitempty"`
	// Signed JWT containing the challenge
	ChallengeToken *string `json:"challenge_token,omitempty"`
}

func (p *PasskeyAuthenticationOptions) GetOptions() *OptionsObj {
	if p == nil {
		return nil
	}
	return p.Options
}

func (p *PasskeyAuthenticationOptions) GetChallengeToken() *string {
	if p == nil {
		return nil
	}
	return p.ChallengeToken
}
