// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UpdateGroupReq struct {
	// The name of the group. Could be a department or a team.
	Name *string `json:"name,omitempty"`
}

func (o *UpdateGroupReq) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
