// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UpdateGroupReq struct {
	// The name of the group. Could be a department or a team.
	Name *string `json:"name,omitempty"`
	// Group's profile image or gradient colors. Supports uploaded image URLs and generated gradient avatars.
	ImageURI *GroupImageURI `json:"image_uri,omitempty"`
}

func (u *UpdateGroupReq) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateGroupReq) GetImageURI() *GroupImageURI {
	if u == nil {
		return nil
	}
	return u.ImageURI
}
