// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UserDetail struct {
	FullName string `json:"full_name"`
	Email    string `json:"email"`
	// User's password
	Password string `json:"password"`
}

func (o *UserDetail) GetFullName() string {
	if o == nil {
		return ""
	}
	return o.FullName
}

func (o *UserDetail) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *UserDetail) GetPassword() string {
	if o == nil {
		return ""
	}
	return o.Password
}
