// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UserVerificationPayload struct {
	// User's password
	Password *string `json:"password,omitempty"`
}

func (u *UserVerificationPayload) GetPassword() *string {
	if u == nil {
		return nil
	}
	return u.Password
}
