// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UserSettingsScopeResponse struct {
	// User setting scope. Values are limited to 64 characters.
	Scope    string         `json:"scope"`
	Settings map[string]any `json:"settings"`
}

func (u *UserSettingsScopeResponse) GetScope() string {
	if u == nil {
		return ""
	}
	return u.Scope
}

func (u *UserSettingsScopeResponse) GetSettings() map[string]any {
	if u == nil {
		return map[string]any{}
	}
	return u.Settings
}
