// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UserDetail struct {
	FullName string `json:"full_name"`
	Email    string `json:"email"`
	// User's password
	Password string `json:"password"`
}

func (u *UserDetail) GetFullName() string {
	if u == nil {
		return ""
	}
	return u.FullName
}

func (u *UserDetail) GetEmail() string {
	if u == nil {
		return ""
	}
	return u.Email
}

func (u *UserDetail) GetPassword() string {
	if u == nil {
		return ""
	}
	return u.Password
}
