// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/internal/utils"
)

type ImageURI struct {
	Original             *string `json:"original,omitempty"`
	Thumbnail32          *string `json:"thumbnail_32,omitempty"`
	AdditionalProperties any     `additionalProperties:"true" json:"-"`
}

func (i ImageURI) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *ImageURI) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *ImageURI) GetOriginal() *string {
	if i == nil {
		return nil
	}
	return i.Original
}

func (i *ImageURI) GetThumbnail32() *string {
	if i == nil {
		return nil
	}
	return i.Thumbnail32
}

func (i *ImageURI) GetAdditionalProperties() any {
	if i == nil {
		return nil
	}
	return i.AdditionalProperties
}

type Properties struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

func (p *Properties) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *Properties) GetValue() string {
	if p == nil {
		return ""
	}
	return p.Value
}

type User struct {
	// User's unique identifier
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
	Email          string `json:"email"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	DisplayName *string `json:"display_name,omitempty"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Name              string  `json:"name"`
	PreferredLanguage string  `json:"preferred_language"`
	Signature         *string `json:"signature,omitempty"`
	// Deprecated! Please use Permissions API instead
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Roles      []string     `json:"roles"`
	ImageURI   *ImageURI    `json:"image_uri,omitempty"`
	Properties []Properties `json:"properties"`
}

func (u *User) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *User) GetOrganizationID() string {
	if u == nil {
		return ""
	}
	return u.OrganizationID
}

func (u *User) GetEmail() string {
	if u == nil {
		return ""
	}
	return u.Email
}

func (u *User) GetDisplayName() *string {
	if u == nil {
		return nil
	}
	return u.DisplayName
}

func (u *User) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *User) GetPreferredLanguage() string {
	if u == nil {
		return ""
	}
	return u.PreferredLanguage
}

func (u *User) GetSignature() *string {
	if u == nil {
		return nil
	}
	return u.Signature
}

func (u *User) GetRoles() []string {
	if u == nil {
		return []string{}
	}
	return u.Roles
}

func (u *User) GetImageURI() *ImageURI {
	if u == nil {
		return nil
	}
	return u.ImageURI
}

func (u *User) GetProperties() []Properties {
	if u == nil {
		return []Properties{}
	}
	return u.Properties
}
