// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/internal/utils"
	"time"
)

type UserSetting struct {
	// User setting scope. Values are limited to 64 characters.
	Scope string `json:"scope"`
	// User setting key. Values are limited to 128 characters.
	Key string `json:"key"`
	// The JSON value of a user setting. Objects are recommended for extensibility, but any JSON value is accepted up to 64 KiB when serialized as JSON.
	Value     any       `json:"value"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (u UserSetting) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UserSetting) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UserSetting) GetScope() string {
	if u == nil {
		return ""
	}
	return u.Scope
}

func (u *UserSetting) GetKey() string {
	if u == nil {
		return ""
	}
	return u.Key
}

func (u *UserSetting) GetValue() any {
	if u == nil {
		return nil
	}
	return u.Value
}

func (u *UserSetting) GetCreatedAt() time.Time {
	if u == nil {
		return time.Time{}
	}
	return u.CreatedAt
}

func (u *UserSetting) GetUpdatedAt() time.Time {
	if u == nil {
		return time.Time{}
	}
	return u.UpdatedAt
}
