// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Results struct {
	// User setting scope. Values are limited to 64 characters.
	Scope string   `json:"scope"`
	Keys  []string `json:"keys"`
}

func (r *Results) GetScope() string {
	if r == nil {
		return ""
	}
	return r.Scope
}

func (r *Results) GetKeys() []string {
	if r == nil {
		return []string{}
	}
	return r.Keys
}

type UserSettingsListResponse struct {
	Results []Results `json:"results"`
}

func (u *UserSettingsListResponse) GetResults() []Results {
	if u == nil {
		return []Results{}
	}
	return u.Results
}
