// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UserVerificationPayload struct {
	// User's password
	Password *string `json:"password,omitempty"`
}

func (o *UserVerificationPayload) GetPassword() *string {
	if o == nil {
		return nil
	}
	return o.Password
}
