// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/internal/utils"
	"time"
)

type Status string

const (
	StatusActive      Status = "Active"
	StatusPending     Status = "Pending"
	StatusDeactivated Status = "Deactivated"
	StatusDeleted     Status = "Deleted"
)

func (e Status) ToPointer() *Status {
	return &e
}
func (e *Status) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Active":
		fallthrough
	case "Pending":
		fallthrough
	case "Deactivated":
		fallthrough
	case "Deleted":
		*e = Status(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Status: %v", v)
	}
}

// OverrideReleaseChannel - This field is used to override the release channel for the user.
type OverrideReleaseChannel string

const (
	OverrideReleaseChannelCanary OverrideReleaseChannel = "canary"
	OverrideReleaseChannelRc     OverrideReleaseChannel = "rc"
	OverrideReleaseChannelStable OverrideReleaseChannel = "stable"
)

func (e OverrideReleaseChannel) ToPointer() *OverrideReleaseChannel {
	return &e
}
func (e *OverrideReleaseChannel) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "canary":
		fallthrough
	case "rc":
		fallthrough
	case "stable":
		*e = OverrideReleaseChannel(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OverrideReleaseChannel: %v", v)
	}
}

// UserV2ImageURI - User's custom profile image
type UserV2ImageURI struct {
	Original             *string `json:"original,omitempty"`
	Thumbnail32          *string `json:"thumbnail_32,omitempty"`
	AdditionalProperties any     `additionalProperties:"true" json:"-"`
}

func (u UserV2ImageURI) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UserV2ImageURI) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UserV2ImageURI) GetOriginal() *string {
	if u == nil {
		return nil
	}
	return u.Original
}

func (u *UserV2ImageURI) GetThumbnail32() *string {
	if u == nil {
		return nil
	}
	return u.Thumbnail32
}

func (u *UserV2ImageURI) GetAdditionalProperties() any {
	if u == nil {
		return nil
	}
	return u.AdditionalProperties
}

// #region class-body-userv2imageuri
// #endregion class-body-userv2imageuri

type UserV2Properties struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

func (u *UserV2Properties) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *UserV2Properties) GetValue() string {
	if u == nil {
		return ""
	}
	return u.Value
}

// #region class-body-userv2properties
// #endregion class-body-userv2properties

type UserV2 struct {
	// User's unique identifier
	ID             *string    `json:"id,omitempty"`
	OrganizationID *string    `json:"organization_id,omitempty"`
	CreatedAt      *time.Time `json:"created_at,omitempty"`
	ActivatedAt    *time.Time `json:"activated_at,omitempty"`
	// User's display name (default: email address)
	DisplayName *string `json:"display_name,omitempty"`
	Status      *Status `json:"status,omitempty"`
	// User's email address
	Email *string `json:"email,omitempty"`
	// User's pending email address
	DraftEmail *string `json:"draft_email,omitempty"`
	// Server-set expiry for the pending email change verification link (ISO 8601). Read-only.
	DraftEmailExpiresAt *time.Time `json:"draft_email_expires_at,omitempty"`
	// Internal: sha256 hash of the active password-reset token. Server-set, never returned in responses.
	PasswordResetTokenHash *string `json:"password_reset_token_hash,omitempty"`
	// Internal: expiry for the active password-reset token (ISO 8601). Server-set, never returned in responses.
	PasswordResetTokenExpiresAt *time.Time `json:"password_reset_token_expires_at,omitempty"`
	// User's department
	Department *string `json:"department,omitempty"`
	// User's phone number
	Phone *string `json:"phone,omitempty"`
	// User's secondary phone number, preferred for communication
	SecondaryPhone *string `json:"secondary_phone,omitempty"`
	// User's multi-factor authentication status
	MfaEnabled *bool `json:"mfa_enabled,omitempty"`
	// Whether the user has TOTP (authenticator app) MFA enabled
	TotpEnabled *bool `json:"totp_enabled,omitempty"`
	// Whether the user has any registered passkeys
	HasPasskeys *bool `json:"has_passkeys,omitempty"`
	// User's phone number verification status
	PhoneVerified *bool `json:"phone_verified,omitempty"`
	// Token used to invite a user to epilot
	Token *string `json:"token,omitempty"`
	// User's email signature
	Signature *string `json:"signature,omitempty"`
	// Whether the user's signature is enabled
	IsSignatureEnabled *bool `json:"is_signature_enabled,omitempty"`
	// User's preferred language
	PreferredLanguage *string `json:"preferred_language,omitempty"`
	// User's start page after login
	CustomStartPage *string `default:"/app/dashboard" json:"custom_start_page"`
	// Navigation unique identifier - a hash of the normalized navigation payload (name + configuration). Identical navigations across orgs will have the same ID.
	CustomNavigation *string `json:"custom_navigation,omitempty"`
	// This field is used to override the release channel for the user.
	OverrideReleaseChannel *OverrideReleaseChannel `json:"override_release_channel,omitempty"`
	// User's feature preferences
	FeaturePreferences map[string]any `json:"feature_preferences,omitempty"`
	// User's custom profile image
	ImageURI                 *UserV2ImageURI `json:"image_uri,omitempty"`
	Favorites                map[string]any  `json:"favorites,omitempty"`
	EmailNotificationSetting map[string]any  `json:"email_notification_setting,omitempty"`
	// Per-notification-type in-app delivery preferences (notification type key -> enabled). Written by the my-account notification settings UI and honored by svc-notification-api at delivery time. Absent or partial keys fall back to each notification type's configured default. Mirrors email_notification_setting for the in-app channel.
	InAppNotificationSetting map[string]any     `json:"in_app_notification_setting,omitempty"`
	Properties               []UserV2Properties `json:"properties,omitempty"`
	// User tags/labels assigned for classification (e.g. label slugs)
	Tags []string `json:"tags,omitempty"`
}

func (u UserV2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UserV2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UserV2) GetID() *string {
	if u == nil {
		return nil
	}
	return u.ID
}

func (u *UserV2) GetOrganizationID() *string {
	if u == nil {
		return nil
	}
	return u.OrganizationID
}

func (u *UserV2) GetCreatedAt() *time.Time {
	if u == nil {
		return nil
	}
	return u.CreatedAt
}

func (u *UserV2) GetActivatedAt() *time.Time {
	if u == nil {
		return nil
	}
	return u.ActivatedAt
}

func (u *UserV2) GetDisplayName() *string {
	if u == nil {
		return nil
	}
	return u.DisplayName
}

func (u *UserV2) GetStatus() *Status {
	if u == nil {
		return nil
	}
	return u.Status
}

func (u *UserV2) GetEmail() *string {
	if u == nil {
		return nil
	}
	return u.Email
}

func (u *UserV2) GetDraftEmail() *string {
	if u == nil {
		return nil
	}
	return u.DraftEmail
}

func (u *UserV2) GetDraftEmailExpiresAt() *time.Time {
	if u == nil {
		return nil
	}
	return u.DraftEmailExpiresAt
}

func (u *UserV2) GetPasswordResetTokenHash() *string {
	if u == nil {
		return nil
	}
	return u.PasswordResetTokenHash
}

func (u *UserV2) GetPasswordResetTokenExpiresAt() *time.Time {
	if u == nil {
		return nil
	}
	return u.PasswordResetTokenExpiresAt
}

func (u *UserV2) GetDepartment() *string {
	if u == nil {
		return nil
	}
	return u.Department
}

func (u *UserV2) GetPhone() *string {
	if u == nil {
		return nil
	}
	return u.Phone
}

func (u *UserV2) GetSecondaryPhone() *string {
	if u == nil {
		return nil
	}
	return u.SecondaryPhone
}

func (u *UserV2) GetMfaEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.MfaEnabled
}

func (u *UserV2) GetTotpEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.TotpEnabled
}

func (u *UserV2) GetHasPasskeys() *bool {
	if u == nil {
		return nil
	}
	return u.HasPasskeys
}

func (u *UserV2) GetPhoneVerified() *bool {
	if u == nil {
		return nil
	}
	return u.PhoneVerified
}

func (u *UserV2) GetToken() *string {
	if u == nil {
		return nil
	}
	return u.Token
}

func (u *UserV2) GetSignature() *string {
	if u == nil {
		return nil
	}
	return u.Signature
}

func (u *UserV2) GetIsSignatureEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.IsSignatureEnabled
}

func (u *UserV2) GetPreferredLanguage() *string {
	if u == nil {
		return nil
	}
	return u.PreferredLanguage
}

func (u *UserV2) GetCustomStartPage() *string {
	if u == nil {
		return nil
	}
	return u.CustomStartPage
}

func (u *UserV2) GetCustomNavigation() *string {
	if u == nil {
		return nil
	}
	return u.CustomNavigation
}

func (u *UserV2) GetOverrideReleaseChannel() *OverrideReleaseChannel {
	if u == nil {
		return nil
	}
	return u.OverrideReleaseChannel
}

func (u *UserV2) GetFeaturePreferences() map[string]any {
	if u == nil {
		return nil
	}
	return u.FeaturePreferences
}

func (u *UserV2) GetImageURI() *UserV2ImageURI {
	if u == nil {
		return nil
	}
	return u.ImageURI
}

func (u *UserV2) GetFavorites() map[string]any {
	if u == nil {
		return nil
	}
	return u.Favorites
}

func (u *UserV2) GetEmailNotificationSetting() map[string]any {
	if u == nil {
		return nil
	}
	return u.EmailNotificationSetting
}

func (u *UserV2) GetInAppNotificationSetting() map[string]any {
	if u == nil {
		return nil
	}
	return u.InAppNotificationSetting
}

func (u *UserV2) GetProperties() []UserV2Properties {
	if u == nil {
		return nil
	}
	return u.Properties
}

func (u *UserV2) GetTags() []string {
	if u == nil {
		return nil
	}
	return u.Tags
}

// #region class-body-userv2
// #endregion class-body-userv2

type UserV2Input struct {
	OrganizationID *string    `json:"organization_id,omitempty"`
	CreatedAt      *time.Time `json:"created_at,omitempty"`
	ActivatedAt    *time.Time `json:"activated_at,omitempty"`
	// User's display name (default: email address)
	DisplayName *string `json:"display_name,omitempty"`
	Status      *Status `json:"status,omitempty"`
	// User's email address
	Email *string `json:"email,omitempty"`
	// User's pending email address
	DraftEmail *string `json:"draft_email,omitempty"`
	// User's department
	Department *string `json:"department,omitempty"`
	// User's phone number
	Phone *string `json:"phone,omitempty"`
	// User's secondary phone number, preferred for communication
	SecondaryPhone *string `json:"secondary_phone,omitempty"`
	// User's multi-factor authentication status
	MfaEnabled *bool `json:"mfa_enabled,omitempty"`
	// Whether the user has TOTP (authenticator app) MFA enabled
	TotpEnabled *bool `json:"totp_enabled,omitempty"`
	// Whether the user has any registered passkeys
	HasPasskeys *bool `json:"has_passkeys,omitempty"`
	// User's phone number verification status
	PhoneVerified *bool `json:"phone_verified,omitempty"`
	// Token used to invite a user to epilot
	Token *string `json:"token,omitempty"`
	// User's email signature
	Signature *string `json:"signature,omitempty"`
	// Whether the user's signature is enabled
	IsSignatureEnabled *bool `json:"is_signature_enabled,omitempty"`
	// User's preferred language
	PreferredLanguage *string `json:"preferred_language,omitempty"`
	// User's start page after login
	CustomStartPage *string `default:"/app/dashboard" json:"custom_start_page"`
	// Navigation unique identifier - a hash of the normalized navigation payload (name + configuration). Identical navigations across orgs will have the same ID.
	CustomNavigation *string `json:"custom_navigation,omitempty"`
	// This field is used to override the release channel for the user.
	OverrideReleaseChannel *OverrideReleaseChannel `json:"override_release_channel,omitempty"`
	// User's feature preferences
	FeaturePreferences map[string]any `json:"feature_preferences,omitempty"`
	// User's custom profile image
	ImageURI                 *UserV2ImageURI `json:"image_uri,omitempty"`
	Favorites                map[string]any  `json:"favorites,omitempty"`
	EmailNotificationSetting map[string]any  `json:"email_notification_setting,omitempty"`
	// Per-notification-type in-app delivery preferences (notification type key -> enabled). Written by the my-account notification settings UI and honored by svc-notification-api at delivery time. Absent or partial keys fall back to each notification type's configured default. Mirrors email_notification_setting for the in-app channel.
	InAppNotificationSetting map[string]any     `json:"in_app_notification_setting,omitempty"`
	Properties               []UserV2Properties `json:"properties,omitempty"`
	// User tags/labels assigned for classification (e.g. label slugs)
	Tags []string `json:"tags,omitempty"`
}

func (u UserV2Input) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UserV2Input) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UserV2Input) GetOrganizationID() *string {
	if u == nil {
		return nil
	}
	return u.OrganizationID
}

func (u *UserV2Input) GetCreatedAt() *time.Time {
	if u == nil {
		return nil
	}
	return u.CreatedAt
}

func (u *UserV2Input) GetActivatedAt() *time.Time {
	if u == nil {
		return nil
	}
	return u.ActivatedAt
}

func (u *UserV2Input) GetDisplayName() *string {
	if u == nil {
		return nil
	}
	return u.DisplayName
}

func (u *UserV2Input) GetStatus() *Status {
	if u == nil {
		return nil
	}
	return u.Status
}

func (u *UserV2Input) GetEmail() *string {
	if u == nil {
		return nil
	}
	return u.Email
}

func (u *UserV2Input) GetDraftEmail() *string {
	if u == nil {
		return nil
	}
	return u.DraftEmail
}

func (u *UserV2Input) GetDepartment() *string {
	if u == nil {
		return nil
	}
	return u.Department
}

func (u *UserV2Input) GetPhone() *string {
	if u == nil {
		return nil
	}
	return u.Phone
}

func (u *UserV2Input) GetSecondaryPhone() *string {
	if u == nil {
		return nil
	}
	return u.SecondaryPhone
}

func (u *UserV2Input) GetMfaEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.MfaEnabled
}

func (u *UserV2Input) GetTotpEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.TotpEnabled
}

func (u *UserV2Input) GetHasPasskeys() *bool {
	if u == nil {
		return nil
	}
	return u.HasPasskeys
}

func (u *UserV2Input) GetPhoneVerified() *bool {
	if u == nil {
		return nil
	}
	return u.PhoneVerified
}

func (u *UserV2Input) GetToken() *string {
	if u == nil {
		return nil
	}
	return u.Token
}

func (u *UserV2Input) GetSignature() *string {
	if u == nil {
		return nil
	}
	return u.Signature
}

func (u *UserV2Input) GetIsSignatureEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.IsSignatureEnabled
}

func (u *UserV2Input) GetPreferredLanguage() *string {
	if u == nil {
		return nil
	}
	return u.PreferredLanguage
}

func (u *UserV2Input) GetCustomStartPage() *string {
	if u == nil {
		return nil
	}
	return u.CustomStartPage
}

func (u *UserV2Input) GetCustomNavigation() *string {
	if u == nil {
		return nil
	}
	return u.CustomNavigation
}

func (u *UserV2Input) GetOverrideReleaseChannel() *OverrideReleaseChannel {
	if u == nil {
		return nil
	}
	return u.OverrideReleaseChannel
}

func (u *UserV2Input) GetFeaturePreferences() map[string]any {
	if u == nil {
		return nil
	}
	return u.FeaturePreferences
}

func (u *UserV2Input) GetImageURI() *UserV2ImageURI {
	if u == nil {
		return nil
	}
	return u.ImageURI
}

func (u *UserV2Input) GetFavorites() map[string]any {
	if u == nil {
		return nil
	}
	return u.Favorites
}

func (u *UserV2Input) GetEmailNotificationSetting() map[string]any {
	if u == nil {
		return nil
	}
	return u.EmailNotificationSetting
}

func (u *UserV2Input) GetInAppNotificationSetting() map[string]any {
	if u == nil {
		return nil
	}
	return u.InAppNotificationSetting
}

func (u *UserV2Input) GetProperties() []UserV2Properties {
	if u == nil {
		return nil
	}
	return u.Properties
}

func (u *UserV2Input) GetTags() []string {
	if u == nil {
		return nil
	}
	return u.Tags
}

// #region class-body-userv2input
// #endregion class-body-userv2input
