// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UserActivationPayload struct {
	// User's display name (default: email address)
	DisplayName *string `json:"display_name,omitempty"`
	// User's password
	Password *string `json:"password,omitempty"`
}

func (u *UserActivationPayload) GetDisplayName() *string {
	if u == nil {
		return nil
	}
	return u.DisplayName
}

func (u *UserActivationPayload) GetPassword() *string {
	if u == nil {
		return nil
	}
	return u.Password
}
