// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"github.com/epilot-dev/terraform-provider-epilot-usergroup/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *UserGroupResourceModel) ToSharedCreateGroupReq() *shared.CreateGroupReq {
	var name string
	name = r.Name.ValueString()

	out := shared.CreateGroupReq{
		Name: name,
	}
	return &out
}

func (r *UserGroupResourceModel) RefreshFromSharedGroup(resp *shared.Group) {
	if resp != nil {
		r.ID = types.StringValue(resp.ID)
		r.Name = types.StringValue(resp.Name)
	}
}
