// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type GroupImageURI struct {
	AdditionalProperties types.String `tfsdk:"additional_properties"`
	Original             types.String `tfsdk:"original"`
	Thumbnail32          types.String `tfsdk:"thumbnail_32"`
}
