// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type GroupImageURI struct {
	AdditionalProperties jsontypes.Normalized `tfsdk:"additional_properties"`
	GradientColors       []types.String       `tfsdk:"gradient_colors"`
	Original             types.String         `tfsdk:"original"`
	Thumbnail32          types.String         `tfsdk:"thumbnail_32"`
	Thumbnail64          types.String         `tfsdk:"thumbnail_64"`
}
