// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type UserV2 struct {
	ActivatedAt              types.String            `tfsdk:"activated_at"`
	CreatedAt                types.String            `tfsdk:"created_at"`
	CustomStartPage          types.String            `tfsdk:"custom_start_page"`
	Department               types.String            `tfsdk:"department"`
	DisplayName              types.String            `tfsdk:"display_name"`
	DraftEmail               types.String            `tfsdk:"draft_email"`
	Email                    types.String            `tfsdk:"email"`
	EmailNotificationSetting map[string]types.String `tfsdk:"email_notification_setting"`
	Favorites                map[string]types.String `tfsdk:"favorites"`
	FeaturePreferences       map[string]types.String `tfsdk:"feature_preferences"`
	ID                       types.String            `tfsdk:"id"`
	ImageURI                 *GroupImageURI          `tfsdk:"image_uri"`
	IsSignatureEnabled       types.Bool              `tfsdk:"is_signature_enabled"`
	MfaEnabled               types.Bool              `tfsdk:"mfa_enabled"`
	OrganizationID           types.String            `tfsdk:"organization_id"`
	OverrideReleaseChannel   types.String            `tfsdk:"override_release_channel"`
	Phone                    types.String            `tfsdk:"phone"`
	PhoneVerified            types.Bool              `tfsdk:"phone_verified"`
	PreferredLanguage        types.String            `tfsdk:"preferred_language"`
	Properties               []GroupProperties       `tfsdk:"properties"`
	SecondaryPhone           types.String            `tfsdk:"secondary_phone"`
	Signature                types.String            `tfsdk:"signature"`
	Status                   types.String            `tfsdk:"status"`
	Token                    types.String            `tfsdk:"token"`
}
